"""Initial Migration

Revision ID: 5fdddf0dc8ff
Revises: 
Create Date: 2025-07-03 17:48:58.463120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fdddf0dc8ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_parts_id'), table_name='vehicle_parts')
    op.drop_table('vehicle_parts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_parts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('part_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('part_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_parts_pkey')),
    sa.UniqueConstraint('part_number', name=op.f('vehicle_parts_part_number_key'))
    )
    op.create_index(op.f('ix_vehicle_parts_id'), 'vehicle_parts', ['id'], unique=False)
    # ### end Alembic commands ###
