"""Recreate vehicle_parts table

Revision ID: ed15dee52cd3
Revises: 5fdddf0dc8ff
Create Date: 2025-07-03 23:31:41.448216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed15dee52cd3'
down_revision: Union[str, Sequence[str], None] = '5fdddf0dc8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
